### ISSUE TITLE
你能更新一下Angular2+ Express部分的代码么。。

### ISSUE THREAD

**Issue by ClickListener** [dongkuo/blog#1]
你好，我是最近才接触Angular2 的前端小白，一直在困扰如何让angular写的前端与后端交互数据，最近拜读了你的有关angular2的博客，其中有一篇使用Angular2 + Express + MongoDB搭建的博客，但是GitHub上的源码还没有更新。 这篇文章在前端部分说的很详细，后端不是太懂。。能发给我源码或者给我解释一下么。。谢谢！

**Comment by dongkuo** [comment]
@ClickListener 
现在就是最新的源码（Tag: v2），Tag: v1是用angular写的，你可以切换到Tag: v1。后端只需要编写API接口即可。

**Comment by ClickListener** [comment]
@dongkuo 谢谢！
